name: air_env
channels:
  - defaults
dependencies:
  - python=3.6
  - ipython
  - matplotlib
  - tqdm
  - rasterio
  - flask
  - tensorflow==2.0
  # - tensorflow-gpu
  
  # Next few, install with conda-forge
  - conda-forge::gdal
  - conda-forge::ibmpairs
  - conda-forge::overpy
  - conda-forge::geopandas

